Feature/low pop
princess-chichie/gittest pull request #10
Opened 2019-05-06 01:43 UTC by UlricVilleneuve

2019-05-10 02:04 UTC, princess-chichie requested changes

2019-05-10 02:04 UTC, princess-chichie commented on Eskillate/Assets/Scripts/Core/LoadAdditiveScene.cs
> +            var test = GameObject.Find("PauseMenuCanvas");
Change variable name.

2019-05-10 02:04 UTC, princess-chichie commented on Eskillate/Assets/Scripts/LowPop/Level.cs
> +        public Poppable GenerateElementNormalOnly()
change scope of the method to private

2019-05-10 02:04 UTC, princess-chichie commented on Eskillate/Assets/Scripts/LowPop/Level.cs
> +            //var screenWidth = Screen.width;
remove dead code

2019-05-10 02:04 UTC, princess-chichie commented on Eskillate/Assets/Scripts/LowPop/Level.cs
> +            var screenWidth = SCREEN_WIDTH;
SCREEN_WIDTH already contains the value of the screen width, there's no need to create a variable.

2019-05-10 02:04 UTC, princess-chichie commented on Eskillate/Assets/Scripts/LowPop/Level.cs
> +        private Vector2 AssignPoppablePosition()
change name to finding poppable position

2019-05-10 02:04 UTC, princess-chichie commented on Eskillate/Assets/Scripts/LowPop/Level.cs
> +            var extraWidth = _slotWidth - 100;
what if extra width is smaller than 0?

2019-05-10 02:04 UTC, princess-chichie commented on Eskillate/Assets/Scripts/LowPop/Level.cs
> +            // Find the row (id / numberSlots in a Row -> rounded down)
Inverted row and column

2019-05-10 02:04 UTC, princess-chichie commented on Eskillate/Assets/Scripts/LowPop/Poppable.cs
> +
remove unwanted code because position will be reassigned later

2019-05-10 02:04 UTC, princess-chichie commented on Eskillate/Assets/Scripts/LowPop/Poppable.cs
> +            textGO.AddComponent<TMPro.TextMeshPro>();
combine this lines into one

2019-05-10 02:04 UTC, princess-chichie commented on Eskillate/Assets/Scripts/LowPop/GameController.cs
> +                Description = "This is level 1.",
this is level 2

2019-05-12 20:55 UTC, UlricVilleneuve commented on Eskillate/Assets/Scripts/LowPop/Level.cs
> +        private Vector2 AssignPoppablePosition()
After reflexion, because we remove the open slot in this function, I think the name AssignPoppablePosition is appropriate.

2019-05-12 21:39 UTC, UlricVilleneuve commented on Eskillate/Assets/Scripts/LowPop/Level.cs
> +            var extraWidth = _slotWidth - 100;
It only happens if we have between 75 and 100 items. Also, I tried with 200 items and they still looked evenly distributed (the entire screen was filled)!

Will not change this.

2020-01-01 22:44 UTC, merged