Feature/level selection
princess-chichie/gittest pull request #12
Opened 2020-01-11 16:49 UTC by UlricVilleneuve

2020-08-19 00:09 UTC, princess-chichie requested changes

2020-08-19 00:09 UTC, princess-chichie commented on Eskillate/Assets/Scripts/Core/LoadAdditiveScene.cs
> +            var sceneLoadedCallback = new SceneLoadedCallback()
do you really need the class scene loaded call back?

2021-05-19 01:04 UTC, UlricVilleneuve commented on Eskillate/Assets/Scripts/DragAndDrop/GameController.cs
> +            // Set Y pos to 1 to be at scrolled to the top
```suggestion
            // Set Y pos to 1 to be scrolled to the top
```

2021-05-19 01:04 UTC, UlricVilleneuve commented on Eskillate/Assets/Scripts/LowPop/GameController.cs
> +            LoadLevel(levelId - 1);
I dont like this. I think the levels ID should reflect their position in the list.

2021-05-19 01:04 UTC, UlricVilleneuve commented on Eskillate/Assets/Scripts/DragAndDrop/ShapeCollision.cs
> +﻿using Core;
Necessary?

2021-05-19 01:04 UTC, UlricVilleneuve commented on Eskillate/Assets/Scripts/DragAndDrop/GameController.cs
> +            LoadLevel(levelId-1);
Same comment as the other file. 
Btw, lots of code repetition, can you find a way to use common code. Maybe that should be done in another PR though.

2021-05-20 00:19 UTC, UlricVilleneuve commented on Eskillate/Assets/Scripts/DragAndDrop/ShapeCollision.cs
> +﻿using Core;
Yes, because AusioScript is now in Core

2021-05-20 00:21 UTC, merged